name: ci

on:
  push:
    branches: main
  pull_request:
    branches: main

jobs:
  build:
    strategy:
      matrix:
        os: [ windows-latest, macos-latest,  ubuntu-latest ]
        toolchain: [nightly]
        deno_version: [1.38.1]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: Swatinem/rust-cache@v2
        with:
          save-if: ${{ github.ref == 'refs/heads/main' }}
      - name: Setup Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
            toolchain: ${{ matrix.toolchain }}
            override: true
      - uses: denoland/setup-deno@v1
        with:
          deno-version: ${{ matrix.deno_version }}
      - name: Setup Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
            toolchain: ${{ matrix.toolchain }}
            override: true
            components: rustfmt, clippy
      - name: Build
        run: cargo build --locked --release
      - name: Test (debug)
        working-directory: ./e2e_test
        run: |
          ../target/release/deno_bindgen -o bindings/mod.ts
          deno test -A --unstable
      - name: Test (release)
        working-directory: ./e2e_test
        shell: bash
        run: |
          rm -rf target
          ../target/release/deno_bindgen -o bindings/mod.ts --release
          deno test -A --unstable
      - name: Bench
        working-directory: ./e2e_test
        shell: bash
        run: deno bench -A --unstable
